export const CREATE_FILE_REQUEST = "CREATE_FILE_REQUEST";
export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const CREATE_FILE_FAIL = "CREATE_FILE_FAIL";

export const GET_FILE_CID_REQUEST = "GET_FILE_CID_REQUEST";
export const GET_FILE_CID_SUCCESS = "GET_FILE_CID_REQUEST";
export const GET_FILE_CID_FAIL = "GET_FILE_CID_REQUEST";
