export const CREATE_SOP_REQUEST = "CREATE_SOP_REQUEST";
export const CREATE_SOP_SUCCESS = "CREATE_SOP_SUCCESS";
export const CREATE_SOP_FAIL = "CREATE_SOP_FAIL";

export const RETRIEVE_SOP_REQUEST = "RETRIEVE_SOP_REQUEST";
export const RETRIEVE_SOP_SUCCESS = "RETRIEVE_SOP_SUCCESS";
export const RETRIEVE_SOP_FAIL = "RETRIEVE_SOP_FAIL";

export const UPDATE_DOC_REQUEST = "UPDATE_DOC_REQUEST";
export const UPDATE_DOC_SUCCESS = "UPDATE_DOC_SUCCESS";
export const UPDATE_DOC_FAIL = "UPDATE_DOC_FAIL";
