export const GET_TRANSACTION_REQUEST = "GET_TRANSACTION_REQUEST";
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS";
export const GET_TRANSACTION_FAIL = "GET_TRANSACTION_FAIL";
export const ADD_TRANSACTION_REQUEST = "ADD_TRANSACTION_REQUEST";
export const ADD_TRANSACTION_SUCCESS = "ADD_TRANSACTION_SUCCESS";
export const ADD_TRANSACTION_FAIL = "ADD_TRANSACTION_FAIL";
export const UPDATE_TRANSACTION_STATUS_REQUEST =
  "UPDATE_TRANSACTION_STATUS_REQUEST";
export const UPDATE_TRANSACTION_STATUS_SUCCESS =
  "UPDATE_TRANSACTION_STATUS_SUCCESS";
export const UPDATE_TRANSACTION_STATUS_FAIL = "UPDATE_TRANSACTION_STATUS_FAIL";
