export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const RETRIEVE_WALLETID_REQUEST = "RETRIEVE_WALLETID_REQUEST";
export const RETRIEVE_WALLETID_SUCCESS = "RETRIEVE_WALLETID_SUCCESS";
export const RETRIEVE_WALLETID_FAIL = "RETRIEVE_WALLETID_FAIL";
